name: "🐛 Bug Report"
description: File a bug report
title: "[Bug] "
labels: ["bug", "triage"]
assignees: ["koc-he"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: hugo-version
    attributes:
      label: Hugo version
      description: What version of Hugo are you using?
      placeholder: ex. v0.111.3
    validations:
      required: true
  # - type: dropdown
  #   id: is-regression
  #   attributes:
  #     label: Is this a regression
  #     multiple: true
  #     options:
  #       - Yes
  #       - No
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Tell us what you expected to see instead of the bug!
      value: "Not to see the bug!"
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a minimal reproduction of the bug
  # - type: dropdown
  #   id: version
  #   attributes:
  #     label: Version
  #     description: What version are you using?
  #     options:
  #       - 0.0.1 (Default)
  #   validations:
  #     required: true
  # - type: dropdown
  #   id: browsers
  #   attributes:
  #     label: What browsers are you seeing the problem on?
  #     multiple: true
  #     options:
  #       - Firefox
  #       - Chrome
  #       - Safari
  #       - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: textarea
    id: other
    attributes:
      label: Anything else?
