name: '✨ Feature Request'
description: Suggest a feature
title: "[Feature Request] "
labels: ["feature request"]
assignees: ["koc-he"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true